전체적인 UI 작업
boostcampwm-2022/android11-almost-there pull request #24
Opened 2022-11-20 16:47 UTC by tnwlsgk1002

## Related Issue

- resolved boostcampwm-2022/android11-almost-there#21

## 작업 내용 요약

## Checklist

- [x] Merge 되는 브랜치가 올바른가?
- [x] Reviewers, Assignees, Labels, Projects, Milestone 설정을 했는가?
- [x] 스스로 코드 리뷰를 충분히 진행했는가?
- [x] 프로젝트의 스타일 가이드라인(컨벤션)을 준수하는가?

2022-11-21 01:34 UTC, fbghgus123 requested changes

2022-11-21 01:34 UTC, fbghgus123 commented on app/src/main/kotlin/com/woory/almostthere/model/PromiseInfoModel.kt
> +}
기존 TimeModel, DateModel 를 Java 에서 지원해주는 클래스로 교체하였습니다

2022-11-21 01:34 UTC, fbghgus123 commented on app/src/main/kotlin/com/woory/almostthere/ui/BaseViewHolder.kt
> +abstract class BaseViewHolder<ITEM : Any, VDB : ViewDataBinding>(
Adapter 에서 ViewType 별로 ViewHolder를 나누기 위해 공통된 클래스를 만들었습니다

2022-11-21 01:34 UTC, fbghgus123 commented on app/src/main/kotlin/com/woory/almostthere/ui/gaming/GamingFragment.kt
> +        behavior.state = BottomSheetBehavior.STATE_HIDDEN
Bottom Sheet을 보이고 숨기게 하는 함수

2022-11-21 01:34 UTC, fbghgus123 commented on app/src/main/res/layout/activity_promises.xml
> +            android:layout_width="match_parent"
0dp로 변경이 필요해봅니다

2022-11-21 01:44 UTC, swjw13 approved these changes

2022-11-21 01:44 UTC, swjw13 commented on app/src/main/kotlin/com/woory/almostthere/ui/promises/PromisesAdapter.kt
> +        return if (promise.gameDateTime > dummyCurrentDate) {
when문으로 작성해주세요~

2022-11-21 01:45 UTC, soulplay95 approved these changes

2022-11-21 01:46 UTC, tnwlsgk1002 reviewed
주말 간 수고하셨습니다!!🤗

2022-11-21 01:46 UTC, tnwlsgk1002 commented on app/build.gradle.kts
> +    implementation("com.jakewharton.threetenabp:threetenabp:1.4.3")
약속 생성 시에 java.util.Date가 필요했는데, 
해당 Date에 최소 api가 걸려있어서 까다로운 작업이었습니다.
threetenabp은 백포팅을 할 수 있도록 도와주는 라이브러리입니다!!

2022-11-21 01:46 UTC, tnwlsgk1002 commented on app/src/main/kotlin/com/woory/almostthere/ui/creatingpromise/CreatingPromiseFragment.kt
> +                viewModel.promiseDate.collectLatest {
저희 코드에서 collect를 굳이 사용할 필요없이 collectLatest로 최신의 데이터만 받아와도 될 것 같아서 수정했습니다.

2022-11-21 01:46 UTC, tnwlsgk1002 commented on app/src/main/kotlin/com/woory/almostthere/ui/creatingpromise/CreatingPromiseFragment.kt
> +                viewModel.promiseTime.collectLatest {
각각을 launch해서 하는 부분은 [다음 공식 문서](https://developer.android.com/topic/libraries/architecture/coroutines#lifecycle-aware)을 참고해서 작성했는데 지금보니 repeatOnLifecycle이 빠져있습니당... flow 좀 더 공부하고 다시 수정해보겠습니다!!!

2022-11-21 01:46 UTC, tnwlsgk1002 commented on app/src/main/kotlin/com/woory/almostthere/ui/promises/PromisesFragment.kt
> +    private val viewModel: PromisesViewModel by viewModels()
어디서는 viewModelProvider를 쓰고 어디서는 by viewModels()를 사용하고 있습니다.
일관성을 위해 다수의 팀원이 조금 더 깔끔하다고 느꼈던 by viewModels로 통일하겠습니다!!

2022-11-21 06:48 UTC, fbghgus123 approved these changes

2022-11-21 07:06 UTC, merged

2022-11-23 06:35 UTC, soulplay95 commented on app/src/main/kotlin/com/woory/almostthere/ui/creatingpromise/CreatingPromiseActivity.kt
> +        binding.containerToolbar.toolbar.title = getString(R.string.promise_creation)
Toolbar title을 XML의 title 속성이 아닌 코드로 지정해주신 이유가 있을까요?

2022-11-23 06:36 UTC, soulplay95 commented on app/src/main/kotlin/com/woory/almostthere/ui/main/MainFragment.kt
> +            val intent = Intent(requireActivity(), CreatingPromiseActivity()::class.java)
CreatingPromiseActivity 내부의 companion object로 해당 화면으로 이동하는 코드를 넣으면 재사용성을 증가시킬 수 있을 것으로 보입니다!

2022-11-23 06:50 UTC, soulplay95 commented on app/src/main/kotlin/com/woory/almostthere/model/DateModel.kt
> +        return "${year}년 ${month}월 ${dayOfMonth}일"
Model 내부에 hard-coded string을 사용하게 되면 다국어 지원이 힘들어보입니다.

[Support different languages and cultures](https://developer.android.com/training/basics/supporting-devices/languages)